### ISSUE TITLE
Can't get attribute Classifier 

### ISSUE THREAD

**Issue by oomensusan** [faresmalik/SEViT#2] opened 2023-01-12 16:55 UTC
Hi Team, 

Can you please confirm which version of mlp and python needs to be installed? I am getting the below error and I believe it could be the version issue, if not can you help, please? Thanks, in advance
![image](https://user-images.githubusercontent.com/8180920/212130611-a0a2d874-0591-4d42-91b2-493c1cb2eb58.png)

**Comment by faresmalik** [comment] 2023-01-13 13:28
Dear, 

The mlp is not a library. If you check ''models'' directory, you will find a script named ''mlp.py" which includes ''Classifier'' class. When you download the MLPs weights, make sure to unzip the file before running the test.py script. 

Please let me know if the issue is still there.

**Comment by oomensusan** [comment] 2023-01-16 13:37
Hi, Apologies for the late reply. I was not able to resolve the issue. 
I tried unzipping the file, but it got unzipped into an archive folder. I am using Windows 11. So shouldn't the file extension be .pth only?
I haven't understood, where the mlp weights have to be uploaded. Is it in the models' folder or should I create another folder and put in the weights? 
And, if I run with the weights in the models folder , I was getting the below error:
Please let me know, if I am doing something wrong.  Thank you
![image](https://user-images.githubusercontent.com/8180920/212691040-c11109a8-6af1-4fd9-bc04-ed6daec90fe8.png)

**Comment by oomensusan** [comment] 2023-01-18 05:53
Can someone update please?

**Comment by faresmalik** [comment] 2023-01-18 09:53
Hi, 

We tried the code, and it's working. One possible solution would be to install the MLP weights separately, put them in one folder, and then pass the path of that directory.

**Comment by faresmalik** [comment] 2023-06-07 06:19
We will close this issue. 

Thank you!

**Closed as completed by faresmalik** 2023-06-07 06:19 UTC
